import type { NextPage } from "next";
import Head from "next/head";

const Connections: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex flex-col h-screen w-full gap-y-4 sm:gap-y-8">
                <h1 className="text-4xl bold text-brandText">Connections</h1>
                <div className="flex flex-col md:flex-row w-full">
                    <div className="flex flex-col space-y-1 bg-white rounded-lg p-6">
                        <div className="flex flex-row">
                            <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" className="w-10 h-10 rounded-md" />
                            <span className="text-lg font-semibold mt-2 ml-1">Notion: </span>
                            <div className="bg-green-400 rounded-full w-4 h-4 mt-[14px] ml-2 animate-pulse"></div>
                            <span className="text-sm font-semibold ml-1 mt-[12px]">Active</span>
                        </div>
                        <div>
                            <button type="submit" className="bg-red-100 text-red-600 disabled:bg-gray-200 disabled:text-gray-500 rounded-md h-8 w-full px-6 mt-3">Disconnect</button>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};

export default Connections;
