import type { NextPage } from "next";
import Head from "next/head";
import UserLoggedInNav from "../components/UserLoggedInNav";

const Dashboard: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex flex-row">
                <nav className="flex-auto hidden sm:block sm:w-[28rem] md:w-[26rem]">
                    <UserLoggedInNav />
                </nav>
                <main className="flex-auto container min-h-screen p-10 px-0 mx-auto md:py-12 md:pl-24 gap-y-8">
                    <div className="px-5">
                        <div className="flex flex-col h-screen w-full gap-y-8">
                            <h1 className="text-4xl bold text-brandText">Dashboard</h1>
                            <div className="bg-white rounded-lg h-1/2 w-full lg:w-3/4"></div>
                        </div>
                    </div>
                </main>
            </div>
        </>
    );
};

export default Dashboard;
