import type { NextPage } from "next";
import Head from "next/head";
import Link from 'next/link'
import IdentityPanel from "../components/identity/identityPanel";
import UserLoggedInNav from "../components/UserLoggedInNav";

const Dashboard: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <nav className="flex flex-row px-2">
                <UserLoggedInNav />
            </nav>

            <div className="container flex flex-col items-center min-h-screen p-10 px-0 mx-auto md:py-20 md:p-10 md:px-0 gap-y-8">
                <main className="p-5 md:p-0">

                </main>
            </div>
        </>
    );
};

export default Dashboard;
