import { UploadIcon } from "@heroicons/react/outline";
import type { NextPage } from "next";
import Head from "next/head";
import { useMemo } from "react";
import { useForm, SubmitHandler } from "react-hook-form";

interface ImportFormInputs {
    file: FileList;
}

const Import: NextPage = () => {
    const { register, handleSubmit, watch, formState: { errors } } = useForm<ImportFormInputs>();
    const onSubmit: SubmitHandler<ImportFormInputs> = async data => {
        console.log(data);
        const res = await fetch('/api/fileupload', {
            method: 'POST',
            body: data.file[0]
        });
        if (res.status === 200) {
            // success
        } else {
            // failure
        }
    }
    const file = watch('file');
    const fileName = useMemo(() => {
        if (file && file.length > 0)
            return file[0]?.name;
        return 'File not uploaded';
    }, [file]);
    return (
        <>
            <Head>
                <title>Import</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex flex-col h-screen w-full lg:w-3/4 items-center gap-y-4 sm:gap-y-8">
                <h1 className="text-4xl bold text-brandText">Import</h1>
                <div className="h-1/2 w-full lg:w-3/4">
                    <form className="flex flex-col gap-y-4 justify-center items-center" onSubmit={handleSubmit(onSubmit)}>
                        <div className="flex flex-col bg-white rounded-lg w-full lg:w-1/2 h-fit py-2">
                            <div className="flex flex-row gap-x-4 mt-1 ml-3">
                                <div className="bg-blue-50 rounded-full p-2 h-10 w-10 mt-1">
                                    <UploadIcon className="h-6 w-6 text-blue-600 " />
                                </div>
                                <div className="flex flex-grow flex-col">
                                    <span className="text-md text-brandText">Your file</span>
                                    <span className="text-sm text-gray-400">{fileName}</span>
                                </div>
                                <input id="fileUpload" className="hidden" type="file" {...register("file", { required: true })} />
                                <label className="bg-blue-50 text-sm rounded-md px-3 mr-4 mt-2 cursor-pointer py-1 h-fit text-blue-600" htmlFor="fileUpload">
                                    Upload
                                </label>
                            </div>
                        </div>
                        {errors.file && <span className="text-red-500 text-sm text-left">File upload is required</span>}
                        <button type="submit" className="bg-blue-100 text-blue-600 disabled:bg-gray-200 disabled:text-gray-500 rounded-md h-10 w-1/4">Submit</button>
                    </form>
                </div>
            </div>
        </>
    );
};

export default Import;
