import type { NextPage } from "next";
import Head from "next/head";
import IdentityPanel from "../components/identity/identityPanel";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="flex flex-row px-2">
        <IdentityPanel />
      </nav>

      <div className="container flex flex-col items-center justify-center min-h-screen p-10 px-0 mx-auto md:py-20 md:p-10 md:px-0 gap-y-8">
        <h1 className="font-extrabold text-center text-7xl">
          Kindle <span className="text-blue-500">Highlights</span>
        </h1>


        <main className="p-5 md:p-0">
          <section className="h-full max-h-72 transform group border-2 border-neutral-800 rounded-2xl duration-300 hover:scale-105 hover:border-blue-600 hover:-translate-y-1 hover:shadow-2xl">
            <a href="https://nextjs.org/" target="_blank" rel="noreferrer">
              <div className="p-5 py-10 flex flex-col justify-center h-full text-center">
                <h2 className="mb-5 text-3xl">Import from file</h2>
                <p className="mb-5">The default way to start importing</p>
                <button className="p-2 px-6 w-fit self-center text-white font-bold bg-blue-500 rounded-full group-hover:bg-blue-600 duration-300">
                  Get Started
                </button>
              </div>
            </a>
          </section>
        </main>
      </div>
    </>
  );
};

export default Home;
